# 1. Performance: Habilita o cache de build.
# O Gradle reutiliza outputs de builds anteriores se nada mudou.
org.gradle.caching=true

# 2. Velocidade: Compilação Paralela.
# Permite que o Gradle execute tarefas independentes ao mesmo tempo.
org.gradle.parallel=true

# 3. Memória do Daemon.
# Define quanto de RAM o "robô" do Gradle pode usar.
# -Xmx2g garante que ele não estoure a memória do CI (que geralmente tem limites)
# mas tenha o suficiente para ser rápido.
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# 4. (Opcional) Aviso de funcionalidades depreciadas.
# Ajuda a manter o projeto pronto para futuras versões do Gradle.
org.gradle.warning.mode=all