name: Java CI with Gradle

# Quando esse pipeline vai rodar?
on:
  push:
    branches: [ "main", "refactor/**", "feat/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest # A máquina virtual do Github

    steps:
      # 1. Baixa o seu código
      - name: Checkout code
        uses: actions/checkout@v6

      # 2. Instala o Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Dá permissão de execução para o Gradle Wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Roda os testes (Unitários e Integração com Testcontainers)
      - name: Build with Gradle and Run Tests
        run: ./gradlew build

      # 5. (Opcional) Publica relatório de testes se falhar
      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: test-report
          path: build/reports/tests/test/

      # 6. Configura o Docker Buildx (Ferramenta moderna de build)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # 7. Autenticação na AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 8. Login no Amazon ECR
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 9. Constrói a imagem Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/vivaldi-bank-api:latest
          #Otimização: Cacheia as camadas para o build ficar rápido
          cache-from: type=gha
          cache-to: type=gha,mode=max
